"""
Pydantic v2 models for DEADPOOL — the startup risk monitoring system.

All data flowing between specialist agents, the Head Agent, and the API layer
is represented by these validated schemas. Pydantic v2 enforces field
constraints at instantiation time, so malformed model responses fail fast
rather than propagating bad data into downstream logic.
"""
from __future__ import annotations

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, Field


class Anomaly(BaseModel):
    """
    A single risk signal detected by a specialist agent.

    Severity and confidence are both normalized to [0, 1]. Severity represents
    how bad the risk is if it materialises; confidence represents how certain
    the agent is that the signal is real. The Head Agent uses both values when
    cross-validating across domains.

    ``cross_references`` names the other agent domains that should corroborate
    this anomaly — e.g., a People anomaly about key-person disengagement should
    be cross-referenced against ``code_audit`` (who owns the code?) and ``infra``
    (which services will stop deploying?).
    """

    id: str
    agent_domain: str  # people | finance | infra | product | legal | code_audit
    severity: float = Field(ge=0.0, le=1.0)
    confidence: float = Field(ge=0.0, le=1.0)
    title: str
    description: str
    affected_entities: list[str] = []
    evidence: dict[str, Any] = {}
    cross_references: list[str] = []  # domains that should corroborate this
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class CascadeNode(BaseModel):
    """
    A single step in a multi-domain failure cascade chain.

    ``conditional_probability`` is the probability this step occurs *given*
    the previous step has already occurred. ``cumulative_probability`` is the
    product of all conditional probabilities from the trigger node to this node.
    Chains are pruned when cumulative_probability drops below 0.25.
    """

    id: str
    agent_domain: str
    title: str
    severity: float = Field(ge=0.0, le=1.0)
    conditional_probability: float = Field(ge=0.0, le=1.0)
    cumulative_probability: float = Field(ge=0.0, le=1.0)
    evidence: str = ""


class CascadeChain(BaseModel):
    """
    A traced multi-step failure path from a trigger anomaly to a terminal risk.

    ``urgency_score`` is computed as: (1 / time_to_impact_days) × severity × (1 − reversibility).
    Higher urgency means act now. ``financial_impact`` is a pre-calibrated USD estimate
    for the specific cascade path. The Head Agent ranks chains by urgency and reports
    the top 3 to the founder.
    """

    id: str
    trigger_anomaly_id: str
    nodes: list[CascadeNode]
    overall_probability: float = Field(ge=0.0, le=1.0)
    time_to_impact_days: int
    financial_impact: float  # USD
    urgency_score: float


class FounderBriefing(BaseModel):
    """
    Structured plain-language briefing generated by the Head Agent for the founder.

    Replaces the previous free-form string briefing. Each field is requested
    explicitly in the Gemini prompt so the response is parseable and renderable
    without further processing. ``recommended_action`` always contains exactly
    ONE specific action — not a list, not vague advice.
    """

    summary: str            # 2-3 sentences on the highest-priority risk
    timeline: str           # e.g. "50 days to financial impact"
    recommended_action: str  # ONE specific action the founder should take now


class RiskScore(BaseModel):
    """
    The primary output of a full DEADPOOL analysis cycle.

    ``score`` is a 0–100 composite derived from cascade urgency (up to 40 pts),
    high-severity anomaly count (up to 40 pts), and baseline average severity
    (up to 20 pts). ``severity_level`` is a human-readable bucketing of the score:
    critical ≥ 75, high ≥ 50, medium ≥ 25, low < 25.

    ``trend`` reflects whether the risk is growing relative to the previous
    analysis cycle. ``top_cascades`` contains at most 3 chains, ranked by urgency.
    """

    score: float = Field(ge=0.0, le=100.0)
    severity_level: Literal["low", "medium", "high", "critical"]
    trend: Literal["increasing", "stable", "decreasing"]
    top_cascades: list[CascadeChain]
    briefing: FounderBriefing
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class AgentReport(BaseModel):
    """
    Output of a single specialist agent run.

    ``anomalies`` is the validated list of risk signals detected in this cycle.
    ``raw_data_summary`` is a brief string describing what data was loaded —
    useful for debugging data-source availability issues without re-running the agent.
    """

    agent: str
    anomalies: list[Anomaly]
    raw_data_summary: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class WhatIfScenario(BaseModel):
    """
    Input and output for a What-If simulation run.

    On input, the caller provides ``scenario_type`` and optional ``parameters``
    (e.g., ``{"severity_multiplier": 1.5}``). The Head Agent modifies the
    relevant anomaly severities, re-runs the full analysis pipeline, and
    populates ``modified_cascades``, ``new_risk_score``, and
    ``comparison_briefing`` in place before returning the same object.

    Supported scenario types:
    - ``engineer_leaves``   — boosts People domain severity
    - ``client_churns``     — boosts Finance domain severity for named client
    - ``cve_discovered``    — boosts Code Audit domain severity
    - ``cloud_costs_double`` — boosts Infra domain severity
    """

    scenario_type: str  # "engineer_leaves" | "client_churns" | "cve_discovered" | "cloud_costs_double"
    parameters: dict[str, Any] = {}
    modified_cascades: list[CascadeChain] = []
    new_risk_score: float | None = None
    comparison_briefing: str = ""
